services:
  app:
    build: .
    container_name: newspapersscrape-app1
    depends_on:
        - mongo
    ports:
        - ${APP_PORT}:5000
    volumes:
        - ./:/app

  mongo:
    image: mongo:latest
    container_name: newspapersscrape-mongo1
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./dump:/dump
      - ./datos_db:/data/db

  mongo-express:
    links:
      - mongo
    image: mongo-express
    container_name: newspapersscrape-mongo-express1
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
